### ISSUE TITLE
Problem with Outlook Web App (Malware in AdBlock Ultimate)

### ISSUE THREAD

**Issue by DerKnecht** [adblockultimate/AdBlockUltimate-firefox#10]
Okay, this is a really creepy issue, but I have this with various installations but the same profile of Firefox Developer Edition.
When this plugin is activated, sending E-Mails via owa (Outlook Web App) of my university causes the spam-filter to prevent sending my mail with the following reason:
'554 rejected due to spam URL in content'
![getfileattachment](https://user-images.githubusercontent.com/10567075/40192700-6cb2a376-5a05-11e8-99f2-105c4f846728.png)
This problem only encounters, when the Plugin "AdBlock Ultimate 2.31" is activated.
The support of my university says there might be an AddOn that adds Spam to my sent mails.
So what and why is this and how does it relate to this AddOn?

**Comment by DerKnecht** [comment]
@adblockultimate 
I suggest you to fix this issue. I also reported this to the mozilla team.

**Comment by adblockultimate** [comment]
Hi DerKnecht

Can you you provide us with the source code of the e-mail sent? You can send it to adblock@adblockultimate.net

**Comment by DerKnecht** [comment]
I am very sorry, but I have no access to the blocked emails. I will sent you the mail address of the support of my university via mail. Maybe they can help you to figure out whats wrong here.

**Comment by adblockultimate** [comment]
Thanks.

**Comment by DerKnecht** [comment]
Why do you close this issue? Is it fixed?

**Comment by DerKnecht** [comment]
Btw: Why there were no commits for 2 years now? Weren't there any changes?

**Comment by lam4o** [comment]
Hi DerKnecht, we don't distribute any malware. We have been distributing the extension for the past 2 years with millions of happy users and highest ratings in Firefox, Chrome, Edge, iOS and Opera. We don't allow whitelisted advertisers, google ads etc - we don't monetize our extension.

If I have to guess. my bet what the problem was, it might be the same as here: https://github.com/adblockultimate/AdBlockUltimate-firefox/issues/9

The extension detected the text box in Outlook as iframe, injected the CSS rules to hide ads and they were included in the mail. From there, your firewall detected them as unusual spam and the mail was blocked.

Anyway, we've contacted your university to let us know if this is the case.

We haven't committed any updates in github because most of the blocking is done via our filters - we update the filters.

Please let me know if you have any other questions. If so, please use our support e-mail at adblock@adblockultimate.net

**Comment by adblockultimate** [comment]
Hi DerKnecht, we don't distribute any malware. We have been distributing the extension for the past 2 years with millions of happy users and highest ratings in Firefox, Chrome, Edge, iOS and Opera. We don't allow whitelisted advertisers, google ads etc - we don't monetize our extension.

If I have to guess. my bet what the problem was, it might be the same as here: https://github.com/adblockultimate/AdBlockUltimate-firefox/issues/9

The extension detected the text box in Outlook as iframe, injected the CSS rules to hide ads and they were included in the mail. From there, your firewall detected them as unusual spam and the mail was blocked.

Anyway, we've contacted your university to let us know if this is the case.

We haven't committed any updates in github because most of the blocking is done via our filters - we update the filters.

Please let me know if you have any other questions. If so, please use our support e-mail at adblock@adblockultimate.net
